quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/biblioteka_db

quarkus.hibernate-orm.database.generation.enabled=true
quarkus.hibernate-orm.database.generation=drop-and-create

# Scheduler configuration
quarkus.scheduler.enabled=true
quarkus.scheduler.start-mode=normal

# Logging
quarkus.log.level=INFO
quarkus.log.category."org.acme".level=DEBUG