quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/biblioteka_db

quarkus.hibernate-orm.database.generation.enabled=true
quarkus.hibernate-orm.database.generation=drop-and-create

# Scheduler configuration
quarkus.scheduler.enabled=true
quarkus.scheduler.start-mode=normal

# Logging
quarkus.log.level=INFO
quarkus.log.category."org.acme".level=DEBUG

# Keycloak / OIDC konfiguracija
quarkus.oidc.auth-server-url=http://localhost:8180/realms/biblioteka
quarkus.oidc.client-id=biblioteka-klijent
quarkus.oidc.credentials.secret=2ZpWt3rgrfAA50z4BnSKp2rM3KW6C8wa
quarkus.oidc.application-type=service
quarkus.oidc.tls.verification=none

# application.properties

quarkus.rest-client."org.example.client.IpifyClient".url=https://api.ipify.org
quarkus.rest-client."org.example.client.TimeApiClient".url=https://timeapi.io

#configKey:
quarkus.rest-client.ipify-api.url=https://api.ipify.org
quarkus.rest-client.timeapi-api.url=https://timeapi.io


quarkus.rest-client."org.examle.client.valutaKlijent".url=https://api.euroratesapi.dev
quarkus.rest-client.euroratesapi-api.url=https://api.euroratesapi.dev